### PR TITLE
Added feature flag for UEK kernel install (#63)

### PR DESCRIPTION
**Pull request by graham1228**
## Testing Evidence:
https://gist.github.com/graham1228/7298cd3ec26840582b6bdb74fcaab9cb

Signed-off-by: Robert Graham <robert.graham@cerner.com>

### CODE REVIEW

**Comment by graham1228** [comment]
@Djelibeybi I submitted the OCA, not sure how long it takes to get approved.

**Comment by Djelibeybi** [comment]
> @Djelibeybi I submitted the OCA, not sure how long it takes to get approved.

And I can see your submission in the queue. However given your employer and our commercial relationship with them, I wouldn't be surprised if the submission was flagged for review by our legal folks and your employers.

**Comment by Djelibeybi** [comment]
@graham1228 you signed your commits using your corporate email address, which has triggered a requirement for a Corporate CLA to be signed by an authorised representative from Cerner. 

Depending on your internal policies, this is either the only option, or you could resubmit this PR using a personal email address and signing an OCA using that email address instead. But you'll need to check if that's allowed at Cerner (it's not at Oracle, for example).

**Comment by graham1228** [comment]
@Djelibeybi Okay, I'm working on tracking down who at Cerner can provide the CLA. Do you know if Cerner and Oracle might already have an existing CLA in place that would cover me?

**Comment by Djelibeybi** [comment]
I will ask my legal contact, but yours should know too. Let's both ask and see if each side agrees with the other. :)

**Comment by graham1228** [comment]
I did find this in our online documentation at Cerner:

> Re: Oracle contributor agreement for Cerner? Apr 14, 2016 11:35 AM
> Well, it took an obscenely long time to get past the lawyers and the paperwork, but: Cerner Corporation is nowlisted as a signatory of the Oracle Contributor Agreement. There should be no further obstacles for Cernerassociates wishing to contribute code to Oracle-sponsored OSS projects (knock on wood).

**Comment by Djelibeybi** [comment]
I've just found the Corporate OCA signed by Cerner listed in on our legacy site. You should still confirm that you have the appropriate permission to submit this code under that OCA, though.

**Comment by Djelibeybi** [comment]
> I did find this in our online documentation at Cerner:

It would be woth adding a note/comment to that internal doc to mention that future submitters should let the Oracle repo maintainers know that the contribution is covered by Cerner's Corporate OCA.

**Review by Djelibeybi — APPROVED** [review]

**Comment by Djelibeybi** [comment]
I've approved the contribution, but I'm going to hold off on merging until you give the all-clear from an approval perspective.

**Comment by graham1228** [comment]
Sounds good, I have a ticket logged with Cerner legal. I'll let you know their answer once I hear back from them.

**Comment by Djelibeybi** [comment]
@graham1228 our shiny new OCA system still has a few rough edges when it comes to Corporate OCAs. When you do find someone in Cerner legal, could you get them to email me with a request to add you to the list of authorised contributors? The self-service interface for this isn't ready yet.

**Comment by graham1228** [comment]
> @graham1228 our shiny new OCA system still has a few rough edges when it comes to Corporate OCAs. When you do find someone in Cerner legal, could you get them to email me with a request to add you to the list of authorised contributors? The self-service interface for this isn't ready yet.

Ok, I'm still trying to get my request routed to the right team. As you know with large companies it can take some time to find the right person/team.

**Comment by graham1228** [comment]
Ok, sounds like I've been added to the Cerner OCA, so this should be good to merge, barring any code review comments.

**Review by Djelibeybi — APPROVED** [review]

**Pull request merged**
